---

ceph_version: 19.2.0
cert_manager_version: 1.16.2
cilium_version: 0.16.22
cilium_helm_version: 1.16.4
containerd_version: 2.0.1
crio_version: 1.31.3
crun_version: 1.19
freeipa_version: 4.12.2

gitea_helm_chart_version: 10.6.0
gitea_version: 1.22.4

harbor_version: 2.12.1
helm_version: 3.16.4

ingress_nginx_version: 4.6.0

keycloak_version: 22.0.1-1
kube_vip_version: 0.8.7
kubernetes_version: 1.31.3

metallb_version: 0.14.8

rook_version: 1.15.6

sealed_secrets_version: 2.17.0
...
